services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped

    env_file:
      - ../../../shared/.env
    environment:
      N8N_LISTEN_ADDRESS: 0.0.0.0
      # App
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      NODE_ENV: ${NODE_ENV}
      WEBHOOK_URL: ${WEBHOOK_URL}

      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${N8N_DB_HOST}
      DB_POSTGRESDB_PORT: ${N8N_DB_PORT}
      DB_POSTGRESDB_DATABASE: ${N8N_DB_NAME}
      DB_POSTGRESDB_USER: ${N8N_DB_USER}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}

      # Timezone
      TZ: ${TZ}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}

    volumes:
      - n8n_data:/home/node/.n8n

    networks:
      - proxy
      - backend

    labels:
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.n8n.rule=Host(`n8n.127.0.0.1.nip.io`)"
      - "traefik.http.routers.n8n.entrypoints=web"

      # Service
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

volumes:
  n8n_data:

networks:
  proxy:
    external: true
  backend:
    external: true
